name: Build and Deploy to GCS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    # Add 'id-token' with 'write' permission for authenticating to GCP
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Use a specific LTS version
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Build Static Site
      run: npm run build

    - name: Authenticate to Google Cloud
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}' # e.g. projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
        service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}' # e.g. my-service-account@my-project.iam.gserviceaccount.com
    
    - name: Deploy to Google Cloud Storage
      id: deploy
      uses: 'google-github-actions/upload-cloud-storage@v2.2.0'
      with:
        parent: false
        path: 'out' # The directory produced by `next build` with `output: 'export'`
        destination: '${{ secrets.GCP_BUCKET_NAME }}' # The GCS bucket to deploy to
        glob: '**' # Upload all files in the source directory

    - name: Make bucket contents public
      run: gcloud storage buckets add-iam-policy-binding gs://${{ secrets.GCP_BUCKET_NAME }} --member=allUsers --role=roles/storage.objectViewer

    - name: Configure static website hosting
      run: gcloud storage buckets update gs://${{ secrets.GCP_BUCKET_NAME }} --web-main-page-suffix=index.html --web-error-page=404.html

    - name: Output public URL
      run: echo "Successfully deployed! View your site at https://storage.googleapis.com/${{ secrets.GCP_BUCKET_NAME }}" 